import type { Metadata } from "next";

import "./globals.css";

import localFont from "next/font/local";

const europaGrotesk = localFont({
  src: [
    {
      path: "../fonts/Europa Grotesk SH Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Europa Grotesk SH Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/Europa Grotesk SH Semi Bold.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-europa-grotesk",
});

const damagePlan = localFont({
  src: [
    {
      path: "../fonts/rollout/Damage Plan.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-damage-plan",
});

const urbanist = localFont({
  src: [
    {
      path: "../fonts/samphora/Urbanist Variable Font wght.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-urbanist",
});

export const metadata: Metadata = {
  // TODO - update metadata
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${europaGrotesk.variable} ${damagePlan.variable} ${urbanist.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="container flex flex-col">
          {children}
        </div>
      </body>
    </html>
  );
}
